### ISSUE TITLE
Are this repository's dependencies needed?

### ISSUE THREAD

**Issue by jgarplind** [pushy/pushy-sdk-web#14]
I was going through my project's dependencies, and found that this library comes with 2 dependencies, one which is very old by now (`whatwg-fetch` has a major 3, you're running v1).

It got me thinking - under what circumstances, if any, are those dependencies required? As far as I know, this library is supposed to run inside web applications, and in 2024 I think it is safe to bet that `fetch` and `Promise` are available.

Not a huge concern, just a potential small improvement to make this library's footprint even smaller.

**Comment by jgarplind** [comment]
Thanks for clarifying your stance!

Would you consider adding an additional way to consume your library so users can choose to opt out of polyfills?

If not, would you consider having them as peerDependencies to let each team resolve them in their own way?

Thanks for being so attentive to user queries, it is much appreciated.

**Comment by pushy** [comment]
Hi @jgarplind,
Upon further investigation, it appears the [Web Push API](https://caniuse.com/?search=push) is not available on older browsers anyway, so polyfilling the fetch and promise APIs isn't beneficial, as the Web Push functionality cannot be polyfilled on these older browsers.

Therefore, we have decided to remove the polyfill dependencies, and have published a new version `1.0.23` without any dependencies.

Please give it a try, and let us know if there's anything else we can help with.
