### ISSUE TITLE
How to know if a device is already registered without calling Pushy.register to get the device token?

### ISSUE THREAD

**Issue by marianolc** [pushy/pushy-sdk-web#4]
Hi! right now I have a secured app that allows the user to accept to receive notifications via pushy. When the user press the button "NOTIFY ME" i will call the Pushy.register and then save the user Id/device token pair in my database. Then when is needed i will send the notification to that user using the registered device token.

Now, I need to make a Settings page for this user. And show the options "DISABLE NOTIFICATIONS" if the device is already registered for that user.

How can I know if that device(browser) is already registered without calling the Pushy.register to get the device token?

**Comment by pushy** [comment]
Hi @marianolc,
Thanks for reaching out. We'd be glad to assist.

You can call `Pushy.isRegistered()` instead, as follows:

```
// Check if the user is registered
if (Pushy.isRegistered()) {
    // User is registered
}
```

To unregister a device from receiving push notifications:

```
// Unregister from notifications
navigator.serviceWorker.getRegistrations().then(function(registrations) {
    for(let registration of registrations) {
        registration.unregister();
    } 
});
```

Please let us know if you have any further inquiries.
