### ISSUE TITLE
Stop receiving notifications programatically

### ISSUE THREAD

**Issue by franciscohanna92** [pushy/pushy-sdk-web#7]
Hi,

The Android SDK has a method called `toggleNotifications` to enable/disable notifications, what would be the way to do it using the Web SDK?

**Comment by pushy** [comment]
Hi @franciscohanna92,
Thanks for reaching out. We'd be glad to assist.

Our recommended approach to toggling notifications on or off per device for our Web Push SDK is to handle it through your backend. To toggle off notifications, send an HTTP request from your web app to your backend, toggling the value of a boolean in your backend database for the specific user which controls whether your backend sends notifications to that device/user via the [Send Notifications API](https://pushy.me/docs/api/send-notifications).

If you're sending notifications to devices using Pub/Sub topics, make sure to unregister them from all their subscribed topics as well:

```
// Check if the user is registered
if (Pushy.isRegistered()) {
    // Unsubscribe the user from all topics
    Pushy.unsubscribe('*').catch(function (err) {
        // Notify user of failure
        alert('Unsubscribe failed: ' + err.message);
    });
}
```

An alternative to controlling this through your backend is to unregister the Pushy service worker entirely using the following code:

```
navigator.serviceWorker.getRegistrations().then(function(registrations) {
    for(let registration of registrations) {
        registration.unregister();
    } 
});
```


Note, however, that subsequent calls to Pushy.register() will assign the device a new Pushy device token. Therefore, it is recommended to manage the notification toggling in your backend instead. 

Please let us know if this makes sense, and if there's anything else we can help with.
