### ISSUE TITLE
Support for iOS Simulator

### ISSUE THREAD

**Issue by noe-david** [pushy/pushy-sdk-web#9]
Hi @pushy!

I am wondering if the web sdk easily could support the iOS Simulator?

If I try to register a device in the Simulator, I get this response from `register`:

```
{
    "code": "INVALID_WEB_PUSH_HOSTNAME",
    "error": "The push notification endpoint hostname (web.sandbox.push.apple.com) is invalid. Please contact support."
}
```

- `pushy-sdk-web` version `1.0.17`
- iOS Simulator on Sonoma, iPhone 15, iOS 17.2

**Comment by pushy** [comment]
Hi @noe-david,
Thanks for reporting this issue. We'd be glad to assist.

We've just fixed the issue on our end by adding support for the iOS Simulator Web Push hostname `web.sandbox.push.apple.com`.

There is no need to update the SDK. Please try to register the device again, and it should work. 🎉

**Comment by noe-david** [comment]
That solved it!

Although, I can't seem to get the push notification to show up on my device. I can see the device registered in my Pushy Dashboard, but when I send a notification, it doesn't show up.

Any ideas? I will continue to investigate if I need to do anything in the simulator.

**Comment by pushy** [comment]
Hi @noe-david,
Glad to hear!

We've gone forth and inspected the response returned by the APNs sandbox server when trying to send a test notification to your iOS Simulator device. The HTTP response code was `201` which indicates success.

Please ensure you are sending notifications to the right device token (starting with `6cd6a3`) returned by `Pushy.register()`, and that you are supplying the following push payload params:

```
{ 
   "data": {
        "title": "Test Notification",
        "url": "https://pushy.me/",
        "message": "Hello World!",
        "image": "https://example.com/image.png"
   }
}
```

You can also use [this page](https://pushy.me/docs/web-push/send-test-notification) to send test notifications.

**Comment by noe-david** [comment]
@pushy thanks for your engagement! 

I didn't have time to pursue this further, and instead found another solution.

**Comment by pushy** [comment]
Hi @noe-david,
Thanks for letting us know.

We've just tested on Sonoma using an M1 Mac running the latest Xcode with iOS Simulator version `17.2` and the registration on the [Pushy Demo page](https://pushy.me/docs/resources/demo) just hung. 

The call to `registration.pushManager.subscribe()` seems to hang on the iOS Simulator. We've seen [similar reports](https://stackoverflow.com/a/76230061/1123355) by other developers.

It's interesting that your iOS Simulator was assigned a token. If you have a moment, could you try visiting [webpushtest.com](https://webpushtest.com/) on your iOS Simulator to see if it's able to register and receive a test notification?

We recommend using a physical device to test iOS Web Push at this time. We cannot find any official Apple docs mentioning that Web Push is supported on any iOS Simulator version.
